# List the start up tasks. Learn more https://www.gitpod.io/docs/config-start-tasks/
tasks:
  - init: echo './src/main/java/Practica5Application.java' # runs during prebuild
    command: echo './src/main/java/Practica5Application.java'

# List the ports to expose. Learn more https://www.gitpod.io/docs/config-ports/
ports:
  - port: 8080
    onOpen: open-preview
